---
databases:
  hosts:
    database:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_user: vagrant
      ansible_ssh_private_key_file: /Users/pmetcalf/dev/mollycat/infra/vagrant/.vagrant/machines/database/virtualbox/private_key
activemqservers:
  hosts:
    activemq:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_user: vagrant
      ansible_ssh_private_key_file: /Users/pmetcalf/dev/mollycat/infra/vagrant/.vagrant/machines/activemq/virtualbox/private_key
